### ISSUE TITLE
Make all file links downloads

### ISSUE THREAD

**Issue by yaaminiv** [RobertsLab/project-oyster-oa#26]
Ex. "Predicted retention times" in SRM protocol

**Comment by yaaminiv** [comment]
@sr320 I couldn't make 2 automatic downloads work:

- FASTA (downloading the FASTA on my computer also adds an extra .txt extension which is undesirable)
- Transition List .csv

Any suggestions?

**Comment by kubu4** [comment]
Links to files?

**Comment by kubu4** [comment]
Or, more specifically, link to what you're working (R script?) on to set up automatic downloads.

**Comment by kubu4** [comment]
Also, could you please clarify on what is not working for the .csv file?

**Comment by yaaminiv** [comment]
@kubu4 

In the first step of my [SRM protocol](https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-09-28-SRM-Skyline-Data-Pipeline.ipynb), I have the user gather all of the materials they need. Steven was able to adjust the link to the Predicted Retention time document in my Jupyter notebook such that it downloaded automatically when I clicked it. I tried to do the same for every other linked file, but it's not working for the .fasta and .csv documents I listed in my other comment.

**Comment by kubu4** [comment]
I've fixed the FASTA file download link.

I'm not experiencing any issues with downloads of either file. Right-click, "Save link as..." on each file link gets me both files in the proper format.

The other files that are in the list cannot be opened by a browser; that's why they do not require a right-click -> "Save link as...". However, a FASTA file (which is a text file) and a CSV file (which is a text file) can both be displayed by a browser. Thus, you have to right-click -> "save link as..." in order to download them.

**Comment by yaaminiv** [comment]
Got it! I'll just include specific right-click/saving instructions for those files then. Thanks @kubu4!
