### ISSUE TITLE
Add all files to repo?

### ISSUE THREAD

**Issue by kubu4** [RobertsLab/project-oyster-oa#28]
In the [017-09-28-SRM-Skyline-Data-Pipeline.ipynb](https://github.com/RobertsLab/project-oyster-oa/blob/master/notebooks/DNR/2017-09-28-SRM-Skyline-Data-Pipeline.ipynb) notebook, why not host all of the files listed in Step 1 in this repo? Of course, the ZIP file of all the RAW files wouldn't work, but all of the individual RAW files are small enough (i.e. <100MB) to be contained in the GitHub repo.

This way, people could just clone/download the entire repo and have all the files without downloading individual files, which is a bit tedious. Additionally, this would simplify writing the R script and referencing files (see Issue #22); you wouldn't have to worry about where people download the files on their computers.

**Comment by yaaminiv** [comment]
My plan is to perfect the pipeline in this repo (my working repository), then move all necessary files over to [my paper repo](https://github.com/RobertsLab/paper-gigas-DNR-proteomics). I'm just hesitant to do that now since I'm having issues with my SRM data and don't know if I'll be able to use it in the paper.
